---
title: "clean_data"
output: pdf_document
date: "2024-01-20"
---

```{r setup, include=FALSE}
library(usethis)
library(gitcreds)
library(tidyverse)
library(ggplot2)
library(knitr)
library(gt)
library(lubridate)
library(dplyr)
```

```{r, include=TRUE}
#clean up data and display important variables

data <- read_csv("Motor Vehicle Collisions with KSI Data - 4326.csv")
head(data)
```

https://cyclingmagazine.ca/sections/news/there-was-a-pro-car-protest-in-high-park-and-it-was-obviously-absolute-chaos/
- protests againt city 

https://phys.org/news/2021-02-toronto-covid-bike-lane-expansion.html
- expansion fo bike lanes due to covid-19 said to find jobs

https://www.bbc.com/news/world-us-canada-44746889
- are toronto streets safe for cycling?

https://www.cbc.ca/news/canada/toronto/toronto-election-vision-zero-1.6605819
- the prize article 
- people die 

1

- not committing
- how to render to pdf?
- toc?
- how to cite chatgpt?
""
```{r, include=FALSE}
cyclists_collisions <- data %>% filter(IMPACTYPE == 'Cyclist Collisions', CYCLIST == "Yes") %>% select(DATE,IMPACTYPE, INVTYPE, INJURY, ACCLASS, CYCLIST)
```

```{r}
cyclists_collisions$DATE <- as.Date(cyclists_collisions$DATE)
cyclists_collisions <- cyclists_collisions %>% arrange(DATE)
col_seasons <- cyclists_collisions %>% mutate(MONTH = month(DATE), SEASON = case_when(month(DATE) %in% c(12, 1 , 2) ~ "Winter", month(DATE) %in% c(3,4,5)~"Spring", month(DATE) %in% c(6,7,8) ~ "Summer", month(DATE) %in% c(9,10,11)~"Fall"))

cyclists_collisions <- col_seasons
```

```{r, include=TRUE}
total_accidents <- cyclists_collisions %>% group_by(SEASON) %>% summarise(count=n())


years <- cyclists_collisions %>% group_by(YEAR = format(DATE, "%Y"))

kable(total_accidents, booktabs = TRUE, col.names = c("Season", "Count"), caption = 'number of cyclist collisions each season')

level_injury <- data.frame(season= cyclists_collisions$SEASON, injury = cyclists_collisions$INJURY, date = cyclists_collisions$DATE)
years
years %>% filter(INJURY == "Fatal" ) %>% summarise(n=n())
```

```{r}
#| echo: false
years %>% ggplot(mapping = aes(x = SEASON, fill = INJURY)) + geom_bar(position = "dodge2") +
  labs(x = "Season", y = "Number ofobservations", fill= "Level of injury") + 
  theme(legend.position = "bottom") +
  facet_wrap(vars(YEAR), scales = "free")

years_sum <- years %>% group_by(YEAR, INJURY) %>% summarise(count=n(), .groups="drop")
years_sum
years_sum %>% ggplot(aes(x = YEAR, y = count, color = INJURY)) + 
  geom_point() +
  geom_line(aes(group = INJURY)) +
  theme_minimal() + labs(x = "Year", y = "Count", caption = "Some bullshit")

```
```{r}
years_sum <- years %>% group_by(MONTH, INJURY) %>% summarise(count=n(), .groups="drop")
years_sum
#years_sum <- years %>% group_by(MONTH, INJURY) %>% mutate(count = n())
#years_sum

new <- years %>% select(MONTH, YEAR, INJURY) %>% filter(YEAR <2010) %>% group_by(MONTH, YEAR, INJURY) %>% summarise(count = n(), .groups = "drop")
new

new %>% ggplot(aes(x = MONTH, y = count, color = INJURY)) + 
  geom_point() +
  geom_line(aes(group = INJURY)) +
  facet_wrap(~YEAR)
  theme_minimal() + labs(x = "Year", y = "Count", caption = "Some bullshit")
```


